/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import conexiones.Conexion;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamaliel Bernal
 */
public class Ciudades extends javax.swing.JFrame {

    ResultSet res;
    Connection conn;
    Conexion conexiones = new Conexion();

    public Ciudades() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        etq = new javax.swing.JLabel();
        nombreCiudad = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));

        panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panel1.setForeground(new java.awt.Color(0, 102, 153));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etq.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        etq.setText("Ciudad");
        panel1.add(etq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, -1, -1));

        nombreCiudad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        panel1.add(nombreCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 28, 114, -1));

        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconfinder_Plus__Orange_34237.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        panel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 81, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Método que agregar una nueva ciudad a la base de datos.
     *
     * @param evt el clic en el botón para confirmar la inserción de la nueva ciudad.
     */
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        try {
            conn = conexiones.Conexion();
            CallableStatement proc = conn.prepareCall("{call NuevaCiudad(?)}");
            proc.setString(1, nombreCiudad.getText());
            int si = proc.executeUpdate();
            if (si != 0) {
                Usuarios s = new Usuarios();
                s.actualizarCiudades();
                conexiones.cierraConexion();
                nombreCiudad.setText("");
            } else {
                System.out.println("Ocurrió un error inesperado :/");
            }
        } catch (SQLException e) {
            System.out.println("Error SQL: ");
            e.printStackTrace(System.out);
            conexiones.cierraConexion();
        } catch (Exception e) {
            System.out.println("Error Genérico: ");
            e.printStackTrace(System.out);
            conexiones.cierraConexion();
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_agregarActionPerformed
    /**
     * Método que se encarga de obtener todas las Ciudades registrados en la base de datos.
     *
     * @return un arrayList con todas las Ciudades registradas en la base de datos.
     * @throws SQLException una consulta no exitosa.
     */

    public ArrayList<String> obtenerCiudades() throws SQLException {
        Statement sql = conexiones.Conexion().createStatement();
        ArrayList<String> arr = new ArrayList<String>();
        ResultSet resultado = sql.executeQuery("SELECT * FROM Ciudades");
        while (resultado.next()) {
            arr.add(resultado.getString("Nombre"));
        }
        conexiones.cierraConexion();
        return arr;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ciudades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel etq;
    private javax.swing.JTextField nombreCiudad;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
