/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

/**
 *
 * @author Samsung
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventas = new javax.swing.JButton();
        inventario = new javax.swing.JButton();
        compras = new javax.swing.JButton();
        mantenimiento = new javax.swing.JButton();
        proveedores = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        articulos = new javax.swing.JButton();
        clientes = new javax.swing.JButton();
        ternicos = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        usuarios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        info = new javax.swing.JButton();
        ayuda = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ventas.setBackground(new java.awt.Color(204, 255, 204));
        ventas.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/venta.png"))); // NOI18N
        ventas.setText("VENTAS");
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        inventario.setBackground(new java.awt.Color(204, 255, 204));
        inventario.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cajas.png"))); // NOI18N
        inventario.setText("MAQUINARIA");
        inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventarioActionPerformed(evt);
            }
        });

        compras.setBackground(new java.awt.Color(204, 255, 204));
        compras.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/carro.png"))); // NOI18N
        compras.setText("COMPRAS");
        compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasActionPerformed(evt);
            }
        });

        mantenimiento.setBackground(new java.awt.Color(204, 255, 204));
        mantenimiento.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/destornillador.png"))); // NOI18N
        mantenimiento.setText("MANTENIMIENTO");
        mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimientoActionPerformed(evt);
            }
        });

        proveedores.setBackground(new java.awt.Color(204, 255, 204));
        proveedores.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/camion-de-reparto (2).png"))); // NOI18N
        proveedores.setText("PROVEDORES");
        proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedoresActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo pantalla_1.png"))); // NOI18N

        articulos.setBackground(new java.awt.Color(204, 255, 204));
        articulos.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        articulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/bolsa-de-la-compra.png"))); // NOI18N
        articulos.setText("ARTÍCULOS");
        articulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articulosActionPerformed(evt);
            }
        });

        clientes.setBackground(new java.awt.Color(204, 255, 204));
        clientes.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/satisfecho.png"))); // NOI18N
        clientes.setText("CLIENTES");
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        ternicos.setBackground(new java.awt.Color(204, 255, 204));
        ternicos.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        ternicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mantenimiento (2).png"))); // NOI18N
        ternicos.setText("TÉCNICOS");
        ternicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ternicosActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(204, 255, 204));
        salir.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iniciar-la-sesion.png"))); // NOI18N
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        usuarios.setBackground(new java.awt.Color(204, 255, 204));
        usuarios.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/hombre.png"))); // NOI18N
        usuarios.setText("USUARIOS");
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("V 1.1.0");

        info.setBackground(new java.awt.Color(204, 255, 255));
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconfinder_Info_Box_Blue_34228 (1).png"))); // NOI18N
        info.setBorder(null);
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        ayuda.setBackground(new java.awt.Color(204, 255, 255));
        ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconfinder_Help_Circle_Blue_34225 (1).png"))); // NOI18N
        ayuda.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(articulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(proveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ternicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mantenimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ventas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clientes)
                                .addGap(11, 11, 11)
                                .addComponent(inventario)
                                .addGap(18, 18, 18)
                                .addComponent(mantenimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(salir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(compras)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usuarios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(articulos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(proveedores)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ternicos)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(fondo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasActionPerformed
        COMPRAS cp = new COMPRAS();
        cp.setVisible(true);
        dispose();
    }//GEN-LAST:event_comprasActionPerformed

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        Usuarios u = new Usuarios();
        u.setVisible(true);
        dispose();
    }//GEN-LAST:event_usuariosActionPerformed

    private void articulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articulosActionPerformed
        Articulos ar = new Articulos();
        ar.setVisible(true);
        dispose();
    }//GEN-LAST:event_articulosActionPerformed

    private void proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedoresActionPerformed
        Proveedores pv = new Proveedores();
        pv.setVisible(true);
        dispose();
    }//GEN-LAST:event_proveedoresActionPerformed

    private void ternicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ternicosActionPerformed
        Tecnicos tc = new Tecnicos();
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_ternicosActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        Ventas ve = new Ventas();
        ve.setVisible(true);
        dispose();
    }//GEN-LAST:event_ventasActionPerformed

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
        Clientes cl = new Clientes();
        cl.setVisible(true);
        dispose();
    }//GEN-LAST:event_clientesActionPerformed

    private void mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimientoActionPerformed
        Mantenimiento ma = new Mantenimiento();
        ma.setVisible(true);
        dispose();
    }//GEN-LAST:event_mantenimientoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Sesion se = new Sesion();
        se.setVisible(true);
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed

    }//GEN-LAST:event_infoActionPerformed

    private void inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventarioActionPerformed
        Maquinaria maq = new Maquinaria();
        maq.setVisible(true);
        dispose();
    }//GEN-LAST:event_inventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton articulos;
    private javax.swing.JButton ayuda;
    private javax.swing.JButton clientes;
    private javax.swing.JButton compras;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton info;
    private javax.swing.JButton inventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mantenimiento;
    private javax.swing.JButton proveedores;
    private javax.swing.JButton salir;
    private javax.swing.JButton ternicos;
    private javax.swing.JButton usuarios;
    private javax.swing.JButton ventas;
    // End of variables declaration//GEN-END:variables
}
